From ubuntu:22.04

WORKDIR /opt/work

COPY  target/release/img-server .

Run chmod +x /opt/work/img-server && \
    useradd -u 1000 img && chown -R 1000:1000 /opt/work/

user 1000

CMD ["/opt/work/img-server"]