name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Run on CentOS 7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker
      run: |
        docker pull centos:7

    - name: Build in CentOS 7 container
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace centos:7 /bin/bash -c "
          curl -o /etc/yum.repos.d/CentOS-Base.repo https://mirrors.aliyun.com/repo/Centos-7.repo &&
          yum clean all && yum makecache &&
          yum -y groupinstall 'Development Tools' &&
          curl https://sh.rustup.rs -sSf | sh -s -- -y &&
          export PATH=$HOME/.cargo/bin:$PATH &&
          rustup default stable &&
          cargo build --release
        "

    - uses: actions/upload-artifact@v4
      with:
        name: Executable Artifact
        path: target/release/img-server
